version: '3.8'

services:
  srsepc:
    container_name: virtual-srsepc
    image: srsran-docker-emulated_srsepc:latest
    command: EPC_CMD_PLACEHOLDER
    networks:
      corenet:
        ipv4_address: PLACEHOLDER_IP
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun

  srsenb:
    container_name: virtual-srsenb
    image: srsran-docker-emulated_srsenb:latest
    command: ENB_CMD_PLACEHOLDER
    networks:
      corenet:
        ipv4_address: PLACEHOLDER_IP
    ipc: shareable
    cap_add:
      - SYS_NICE
    volumes:
      - VOLUME_PLACEHOLDER
      
  srsue:
    image: srsran-docker-emulated_srsue:latest
    command: UE_CMD_PLACEHOLDER
    ipc: service:srsenb
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    depends_on:
      - srsenb
    container_name: virtual-srsue

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24 # Change subnet and above IPS to run multiple environments
        
